#!/bin/bash
set -eo pipefail

# Required to run within IntelliJ, which does NOT inheret user environment
export JAVA_HOME="$HOME/.local/share/mise/installs/java/23"
export PATH="$JAVA_HOME/bin:$PATH"

# Capture staged Java/Kotlin files
FORMATTABLE_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.java$|\.kt$|\.kts$')

if [[ -n "$FORMATTABLE_FILES" ]]; then
  # Execute Spotless validation
  ./gradlew :spotlessCheck || {
    echo "Commit blocked: Formatting violations detected"
    echo "Run './gradlew :spotlessApply' to resolve"
    exit 1
  }
fi
