#!/bin/bash
set -eo pipefail

# Required to run within IntelliJ, which does NOT inherit user environment
export JAVA_HOME="$HOME/.local/share/mise/installs/java/23"
export PATH="$JAVA_HOME/bin:$PATH"

# Capture staged Java/Kotlin files
FORMATTABLE_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.java$|\.kt$|\.kts$')

if [[ -n "$FORMATTABLE_FILES" ]]; then
  echo "Formatting staged Java/Kotlin files..."

  # Execute Spotless to apply formatting
  ./gradlew :spotlessApply

  # Re-stage the formatted files
  echo "Re-staging formatted files..."
  echo "$FORMATTABLE_FILES" | xargs git add

  echo "Formatting complete. You may now commit your changes."
fi
